### ISSUE TITLE
clock_ui.cpp: error: expected class-name before '{' token 

### ISSUE THREAD

**Issue by daniel-kelley** [daniel-kelley/gac#22]
Build error in test target with recent faust update:

    faust2jaqt -I ../lib clock_ui.dsp                                                                                                             
    clock_ui.cpp:8808:67: error: expected class-name before '{' token                                                                             
    8808 | class jackaudio_midi : public jackaudio, public jack_midi_handler {                                                                   
         |                                                                   ^ 

Problem is with stale copy of 'test/faust/audio/jack-dsp.h'.

**Comment by daniel-kelley** [comment]
Also:

    Starting program: /home/dkelley/work/dak/faust/gac/test/test_gac_002_driver -n 1000000
    This GDB supports auto-downloading debuginfo from the following URLs:
    https://debuginfod.fedoraproject.org/ 
    Enable debuginfod for this session? (y or [n]) 
    Debuginfod has been disabled.
    To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib64/libthread_db.so.1".
    Seed: 1804289383
    Program received signal SIGFPE, Arithmetic exception.
    0x000000000042fa18 in computemydsp (dsp=0x47d2a0, count=64, inputs=0x7fffffffd960, outputs=0x7fffffffd950) at
    test_gac_002_driver.c:6939
    6939                            float fElse90 = dsp->fConst0 / fTemp99;
    Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-30.fc35.x86_64
    (gdb) where
    #0  0x000000000042fa18 in computemydsp (dsp=0x47d2a0, count=64, inputs=0x7fffffffd960, outputs=0x7fffffffd950) at  test_gac_002_driver.c:6939
    #1  0x0000000000438a0d in main (argc=3, argv=0x7fffffffdb48) at test_gac_002_driver.c:7583
    (gdb) print dsp->fConst0
    $1 = 44100
    (gdb) print fTemp99
    $2 = 0
    (gdb) print fThen89
    $3 = 0
    (gdb) print fTemp98
    $4 = 0
    (gdb) print fSlow401
    $5 = 6550.71631
